name: tests

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  headless-neovim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          version: stable
          neovim: true
      - name: Run tests
        run: nvim --headless -n -i NONE -u tests/minimal_init.lua -l tests/run.lua
